/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceUsuario;

import DomainModel.Aluno;
import Negocio.AlunoBO;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paulo_000
 */
public class FrmListaAluno extends javax.swing.JInternalFrame {
    AlunoBO bo;
    /**
     * Creates new form FrmListaAluno
     */
    public FrmListaAluno() {
        initComponents();
        bo = new AlunoBO();
        
        List<Aluno> alunos = bo.listarTodos();
        
        preencheTabela(alunos);
    }
    
    private void preencheTabela(List<Aluno> lista) {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id");
        model.addColumn("Nome");
        model.addColumn("CPF");
        model.addColumn("RG");
        model.addColumn("Telefone");
        model.addColumn("Email");
        model.addColumn("Media");
        model.addColumn("Id Curso");
        model.addColumn("Nome Responsavel");
        model.addColumn("Telefone Responsavel");
        
        for (Aluno a : lista) {
            Vector valores = new Vector();
            valores.add(0,a.getIdAluno());
            valores.add(1,a.getNome());
            valores.add(2,a.getCpf());
            valores.add(3,a.getRg());
            valores.add(4,a.getTelefone());
            valores.add(5,a.getEmail());
            valores.add(6,a.getMedia());
            valores.add(7,a.getIdcurso());
            valores.add(8,a.getNomeresp());
            valores.add(9,a.getTelefoneresp());
            
            model.addRow(valores);
        }
        TblListaAlunos.setModel(model);
        TblListaAlunos.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlListaAluno = new javax.swing.JPanel();
        SpnlListaAluno = new javax.swing.JScrollPane();
        TblListaAlunos = new javax.swing.JTable();
        TxtPesquisar = new javax.swing.JTextField();
        BtnPesquisar = new javax.swing.JButton();
        BtnVoltar = new javax.swing.JButton();

        setTitle("Listar Alunos");

        PnlListaAluno.setBackground(new java.awt.Color(255, 255, 255));
        PnlListaAluno.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listar Alunos ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 3, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        TblListaAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "CPF", "RG", "Telefone", "Email", "Media", "Id do Curso", "Responsavel", "Telefone do Respossavel"
            }
        ));
        TblListaAlunos.getTableHeader().setReorderingAllowed(false);
        TblListaAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblListaAlunosMouseClicked(evt);
            }
        });
        SpnlListaAluno.setViewportView(TblListaAlunos);

        BtnPesquisar.setText("Pesquisar");
        BtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPesquisarActionPerformed(evt);
            }
        });

        BtnVoltar.setText("Voltar");
        BtnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlListaAlunoLayout = new javax.swing.GroupLayout(PnlListaAluno);
        PnlListaAluno.setLayout(PnlListaAlunoLayout);
        PnlListaAlunoLayout.setHorizontalGroup(
            PnlListaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlListaAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlListaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlListaAlunoLayout.createSequentialGroup()
                        .addComponent(SpnlListaAluno, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlListaAlunoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(PnlListaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlListaAlunoLayout.createSequentialGroup()
                                .addComponent(TxtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(BtnPesquisar)
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlListaAlunoLayout.createSequentialGroup()
                                .addComponent(BtnVoltar)
                                .addContainerGap())))))
        );
        PnlListaAlunoLayout.setVerticalGroup(
            PnlListaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlListaAlunoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(PnlListaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnPesquisar))
                .addGap(26, 26, 26)
                .addComponent(SpnlListaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(BtnVoltar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PnlListaAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PnlListaAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TblListaAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblListaAlunosMouseClicked
        Object valor = TblListaAlunos.getValueAt( TblListaAlunos.getSelectedRow(), 0);
        Aluno a = bo.Abrir((int)valor);
        FrmEditarAluno janela = new FrmEditarAluno(a, bo);
        this.getParent().add(janela);
        janela.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_TblListaAlunosMouseClicked

    private void BtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPesquisarActionPerformed
        Aluno a = new Aluno();
        a.setNome(TxtPesquisar.getText());
                
        List<Aluno> lista = bo.buscar(a);
        
        preencheTabela(lista);
    }//GEN-LAST:event_BtnPesquisarActionPerformed

    private void BtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltarActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "Deseja Sair?") 
                == 0){
            this.dispose();
        }
    }//GEN-LAST:event_BtnVoltarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnPesquisar;
    private javax.swing.JButton BtnVoltar;
    private javax.swing.JPanel PnlListaAluno;
    private javax.swing.JScrollPane SpnlListaAluno;
    private javax.swing.JTable TblListaAlunos;
    private javax.swing.JTextField TxtPesquisar;
    // End of variables declaration//GEN-END:variables
}
